# Site settings
title: Antonio Fullone
email: antonio@antoniofullone.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/"
url: "http://antoniofullone.com"
twitter_username: lastwebdesigner
github_username:  lastwebdesigner

# Build settings
markdown: kramdown
permalink: pretty
