# Site settings
title: Antonio Fullone
email: antonio.fullone@gmail.com
description: 'Antonio Fullone personal website'
baseurl: ''
url: 'http://antoniofullone.com'
twitter_username: _antoniofullone
github_username: antoniofull
ftp_host: 'antoniofullone.com'
ftp_dir: '/t'
ftp_passive: false
plugins: ['']
exclude: ['node_modules', 'package.json', 'README.md']
permalink: pretty
future: false
