# Site settings
title: Antonio Fullone
email: antonio@antoniofullone.com
description: "Antonio Fullone personal website"
baseurl: ""
url: "http://antoniofullone.com"
url: "http://antoniofullone.com"
twitter_username: lastwebdesigner
github_username:  lastwebdesigner
ftp_host: 'antoniofullone.com'
ftp_dir: '/t'
ftp_passive: false
plugins: ["emoji_for_jekyll"]
exclude: ['node_modules', 'bower_components', 'gulpfile.js', 'grunt_package.json', 'package.json', 'bower.json', 'Gruntfile.js', 'README.md','gulp']
plugins:
  - jekyll-sitemap
  - gemoji
  - jekyll-seo-tag
  - jemoji
# Build settings
markdown: kramdown
permalink: pretty
future: false
